### ISSUE TITLE
WebHooks (sending / receiving)

### ISSUE THREAD

**Issue by sabisasam** [finnerds/bisa-tutorial#19]
A webHook is an HTTP callback: an HTTP POST that occurs when something happens; a simple event-notification via HTTP POST. A web application implementing webHooks will POST a message to a URL when certain things happen.

In other words, a webhook is a way for an app to provide other applications with real-time information. A webhook delivers data to other applications as it happens, meaning you get data immediately.

The following pages are related to this:

## Receiving Data
- [x] https://medium.com/@raiderrobert/how-to-make-a-webhook-receiver-in-django-1ce260f4efff
## Sending Data
- [x] https://zapier.com/engineering/introducing-resthooksorg/ (basics about rest-hook)
### with Redis
- [x] https://github.com/pydanny/dj-webhooks
### with Celery (not prefered, should be done with Django-Channels/Celery||RabbitMQ)
- [x] https://github.com/zapier/django-rest-hooks (sending data to a 3rd party)
- [x] http://resthooks.org/docs/?utm_source=zapier.com&utm_medium=referral&utm_campaign=zapier
### Generic idea for History of Hooks send (can be used in both repositories above)
- [x] https://github.com/zapier/resthookdemo/blob/master/resthookdemo/hooks/models.py

**Comment by dkdndes** [comment]
- [ ] save webhook setup in model
- [ ] save webhook received data in model
- [ ] save webhook send data in model

**Comment by dkdndes** [comment]
@sabisasam close above the topic you completed with the last merge!
